const D=window.HANA_DATA,M=D.menu,I=window.HANA_IMAGES,T=D.T,$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let lang=localStorage.hanaLang||"en",cart=JSON.parse(localStorage.hanaCart||"[]"),current=null;
const tr=k=>T[lang][k]||k,n=id=>T[lang].names[id]||id,d=id=>T[lang].desc[id]||"";
function apply(){document.documentElement.lang=lang;$$("[data-t]").forEach(e=>e.textContent=tr(e.dataset.t));$("#seat").placeholder=tr("seatPlaceholder");$("#langBtn").textContent="🌐 "+lang.toUpperCase();$("#hero").style.backgroundImage=`linear-gradient(90deg,rgba(248,241,231,.98),rgba(248,241,231,.82) 48%,rgba(248,241,231,.25)),url("${I.hero}")`;render();renderCart()}
$$("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.hanaLang=lang;$("#gate").classList.add("hide");apply()});$("#langBtn").onclick=()=>$("#gate").classList.remove("hide");
function card(x){return `<article class="card"><button class="photo" onclick="detail('${x.id}')"><img src="${I[x.img]}"><span class="pill">${tr("details")}</span></button><div class="cardBody"><h3>${n(x.id)}</h3><div class="desc">${d(x.id)}</div><button class="add ${cart.includes(x.id)?"active":""}" onclick="toggle('${x.id}')">${cart.includes(x.id)?tr("added"):tr("add")}</button></div></article>`}
function render(){["carb","main","side","dessert"].forEach(c=>$("#"+c).innerHTML=M.filter(x=>x.cat===c).map(card).join(""));$("#drink").innerHTML=M.filter(x=>x.cat==="drink").map(x=>`<div class="drink ${cart.includes(x.id)?"sel":""}" onclick="detail('${x.id}')"><i>${x.emoji}</i><strong>${n(x.id)}</strong></div>`).join("");$("#special").innerHTML=T[lang].specials.map(s=>`<div class="special"><span>${s[0]}</span><div><b>${s[1]}</b><small>${s[2]}</small></div></div>`).join("")}
function save(){localStorage.hanaCart=JSON.stringify(cart)}window.toggle=id=>{cart.includes(id)?cart=cart.filter(x=>x!==id):cart.push(id);save();render();renderCart();toast(cart.includes(id)?tr("added"):n(id)+" ✓")};
window.detail=id=>{current=id;let x=M.find(y=>y.id===id);$("#mName").textContent=n(id);$("#mDesc").textContent=d(id);$("#media").innerHTML=x.img?`<img src="${I[x.img]}">`:`<div>${x.emoji||"🍽️"}</div>`;$("#mAdd").textContent=cart.includes(id)?tr("added"):tr("add");$("#detail").classList.add("show")};
$("#detailClose").onclick=()=>$("#detail").classList.remove("show");$("#detail").onclick=e=>{if(e.target===$("#detail"))$("#detail").classList.remove("show")};$("#mAdd").onclick=()=>{toggle(current);$("#mAdd").textContent=cart.includes(current)?tr("added"):tr("add")};
function openCart(){$("#drawer").classList.add("show");$("#shade").classList.add("show")}function closeCart(){$("#drawer").classList.remove("show");$("#shade").classList.remove("show")}$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#shade").onclick=closeCart;
function renderCart(){$("#count").textContent=cart.length;$("#cartItems").innerHTML=!cart.length?`<div style="text-align:center;padding:60px;color:#888">🛒<br><br>${tr("cartEmpty")}</div>`:cart.map(id=>{let x=M.find(y=>y.id===id),m=x.img?`<img class="thumb" src="${I[x.img]}">`:`<div class="thumb">${x.emoji}</div>`;return `<div class="row">${m}<strong>${n(id)}</strong><button onclick="removeItem('${id}')">×</button></div>`}).join("");$("#seatSummary").textContent=`${tr("seat")}: ${($("#seat").value||"—").toUpperCase()} · ${tr("items")}: ${cart.length}`}
window.removeItem=id=>{cart=cart.filter(x=>x!==id);save();render();renderCart()};$("#clearBtn").onclick=()=>{cart=[];save();render();renderCart()};$("#seat").value=localStorage.hanaSeat||"";$("#seat").oninput=e=>{e.target.value=e.target.value.toUpperCase().replace(/[^0-9A-Z]/g,"");localStorage.hanaSeat=e.target.value;renderCart()};
$("#orderBtn").onclick=()=>{let s=$("#seat").value.trim().toUpperCase();if(!s){toast(tr("seatRequired"));return}if(!cart.length){toast(tr("cartEmpty"));return}let o="HN"+String(Date.now()).slice(-6);$("#receipt").innerHTML=`<div><span>${tr("orderNo")}</span><b>${o}</b></div><div><span>${tr("seat")}</span><b>${s}</b></div><div><span>${tr("items")}</span><b>${cart.length}</b></div>`;closeCart();$("#confirm").classList.add("show")};$("#doneBtn").onclick=()=>$("#confirm").classList.remove("show");
$("#qrBtn").onclick=()=>{let u=location.href;$("#qrUrl").textContent=u;$("#qrImage").src="https://api.qrserver.com/v1/create-qr-code/?size=440x440&margin=8&data="+encodeURIComponent(u);$("#qr").classList.add("show")};$("#qrClose").onclick=()=>$("#qr").classList.remove("show");$("#qr").onclick=e=>{if(e.target===$("#qr"))$("#qr").classList.remove("show")};
function toast(m){let e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),1600)}apply();renderCart();